### ISSUE TITLE
menu isnt based off of the newest version/ doesnt account for widescreen

### ISSUE THREAD

**Issue by GameMasterPDX** [NotSoDevy/The-Sonic-Debut-Experience#1]
Title says enough
https://media.discordapp.net/attachments/999081575834726441/1066052431491907604/Screenshot_20230120-125122_Sonic_1_Forever.jpg

**Comment by soupnuts6061** [comment]
odd, doesn't occur on pc

**Comment by GameMasterPDX** [comment]
i think widescreen is only supported on mobile maybe

**Comment by soupnuts6061** [comment]
what

**Comment by GameMasterPDX** [comment]
wdym what
